development:
 adapter: mysql
 database: depot_development
 username: root
 password:
 host: 127.0.0.1


test:
 adapter: mysql
 database: depot_test
 username: root
 password:
 host: 127.0.0.1


production:
 adapter: mysql
 database: depot_production
 username: root
 password:
 host: 127.0.0.1


